name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  AWS_REGION: 'us-east-1'  # Specify your AWS region
  S3_BUCKET: 'your-frontend-app-${{ github.event.inputs.environment }}'  # 
Adjust based on your naming convention

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      
      - name: Terraform Plan
        run: |
          terraform init
          terraform plan -var="environment=${{ 
github.event.inputs.environment }}"

  build_and_deploy:
    needs: terraform_plan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION
      
      - name: Build and Deploy
        run: |
          # Add commands to build your frontend application
          # aws s3 sync ./build s3://$S3_BUCKET --delete
          echo "Deployed to S3 Bucket: $S3_BUCKET"
      
      # Add steps for version bumping, creating git tags, and GitHub 
releases

